name: Build and Push Docker Image

# When should this run?
on:
  push:
    branches: [ main ]  # Run when code is pushed to main branch

# What jobs should run?
jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use Ubuntu computer

    steps:
      # Step 1: Get the code from your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Logging into ${{ secrets.DOCKER_USERNAME }} Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # Step 4: Push image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
